### PR TITLE
Style focused button; improve focused radio

### PR DESCRIPTION
**Pull request by agarzola**
This PR sets the button `:hover` styles to also serve as the `:focus` styles. It also modifies the radio element styles to only animate on hover or focus, to indicate to the user that the radio element is in focus.

### CODE REVIEW

**Comment by scottaohara** [comment]
closes #22

**Comment by agarzola** [comment]
I did not realize you had a PR open, @scottaohara. 🙌

**Comment by BcRikko** [comment]
Thanks 🙇  
LGTM 🎉 

I will resolve conflicts 🔧

**Pull request merged**
