### PR TITLE
README English translation

### PR DESCRIPTION
**Pull request by Baldomo**
I translated the original README in English as best as I could. I'll be waiting for feedback as I don't really know Japanese. I also updated the directory listing with symbols from `tree` and linked the two READMEs to each other with the links on top.

PS: I left the TODOs in Japanese, I don't think users would find them useful.

### CODE REVIEW

**Comment by BcRikko** [comment]
Thanks 😍 

I merged #31 , could you check again? 🙏 
It's OK to split README(English-only and Japanese-only) 👍

**Comment by Baldomo** [comment]
I will update my fork once I'm back home

**Comment by Baldomo** [comment]
@BcRikko I pulled the new READMEs from master and split them, let me know.

**Comment by BcRikko** [comment]
Thanks 🙇 
LGTM 🎉

**Pull request merged**
