### PR TITLE
swapped primary and success button styling

### PR DESCRIPTION
**Pull request by KeevanDance**
Double check my work, I'm new to these contributions...

This is meant to solve this issue #19

### CODE REVIEW

**Comment by BcRikko** [comment]
Thanks 🙇 
LGTM 🎉 

Is it OK to merge this PR? 🤔

**Comment by KeevanDance** [comment]
@BcRikko Yeah good with me :) accidentally closed it so I reopened it!

**Comment by BcRikko** [comment]
oh, I see 😆 
Thanks 🎉

**Pull request merged**
